version: '3'
services:
  chirpstack-gateway-os:
    build:
      context: .
      dockerfile: Dockerfile-devel
      args:
        USER_ID: ${UID}
        GROUP_ID: ${GID}
    volumes:
      - .:/workdir
    ulimits:
      nofile:
        soft: 1024
        hard: 262144
    environment:
      - QUILT_PATCHES=/workdir/conf/patches
